// Generated by Wrangler on Fri Jul 26 2024 19:24:41 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_IMAGES_API_TOKEN: string;
	CLOUDFLARE_IMAGE_BASE_URL: string;
}
